### ISSUE TITLE
JSON values should be escaped

### ISSUE THREAD

**Issue by gliljas** [sendgrid/smtpapi-csharp#4]
Since the SendGrid API requires UTF-8 values to be escaped in the JSON structures, this should be handled by Utils.cs. Possibly by using JSON.NET and proper serialization settings.

**Comment by brandonmwest** [comment]
So I've found that SMTP will accept unicode directly without escaping, in both the subject and body, but the BodyEncoding and SubjectEncoding must be set to UTF-8. 

However, when sending via HTTP, ASCII escape sequences need to be used.

Since escape sequences work in both scenarios, I'm going to go ahead and escape everything in this library via Utils.cs. We'll work on a proper refactor to JSON.NET soon.
