### ISSUE TITLE
How to configure everything?

### ISSUE THREAD

**Issue by AleAmla987** [sendgrid/smtpapi-csharp#87]
As I have to set up the account, I bought a domain to send emails and I'll check it out but I do not know how to make it send the email by smtp

**Comment by thinkingserious** [comment]
Hello @AleAmla987,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
